### ISSUE TITLE
MacOS Compiler / SDK on Github

### ISSUE THREAD

**Issue by Haydnspass** [TuragaLab/SplinePSF#6]
@olbris I think the problem with the macOS runner is the version of the SDK in combination with the clang version I set in the build config. I had to change the version on my local machine as well.

Let's do it like this: https://github.com/adc-connect/adcc/blob/041cdcb16ec60d1655db8d562ef2f3b53038c120/.github/workflows/publish.yaml#L48

Then I will need to set the `CONDA_BUILD_SYSROOT` and I need to pass this to CMake.
This way it should work irrespective of any changes of the macOS runner.

**Comment by olbris** [comment]
@Haydnspass Sorry for taking so long to reply. I think your plan will work. That repo seems to be the standard place to get the old Mac OS SDKs. I can have that installed and any environment variables set that your build needs. 

The example you linked above installs the SDK in /Users/runner, but if someplace else is more convenient, let me know.
